---
title: Data classes
author: R package build
date: '2022-02-23'
slug: data-classes
categories: []
tags: []
---
## Data classes

```{r}
library(tidyverse)
```

## Get Data
```{r}
cat_lovers <- read_csv("https://raw.githubusercontent.com/tadla55/tidyverse/main/cat-lovers.csv")
hotels <- read_csv("https://raw.githubusercontent.com/tadla55/tidyverse/main/hotels.csv")
```


## Factors
```{r}
x <- factor(c("BS", "MS", "PhD", "MS"))
x
```

```{r}
typeof(x)
```

```{r}
class(x)
```

```{r}
glimpse(x)
```

```{r}
as.integer(x)
```

## Dates

```{r}
y <- as.Date("2020-01-01")
y
```

```{r}
typeof(y)
```

```{r}
class(y)
```

```{r}
as.integer(y)
```

```{r}
as.integer(y) / 365 # roughly 50 yrs
```

## Data frames

```{r}
df <- data.frame(x = 1:2, y = 3:4)
df
```

```{r}
typeof(df)
```

```{r}
class(df)
```
##Lists

```{r}
l <- list(
  x = 1:4,
  y = c("hi", "hello", "jello"),
  z = c(TRUE, FALSE)
)
l
```

```{r}
df %>%
  pull(y)
```
## Working with factors
 
```{r}
glimpse(cat_lovers)
```

```{r}
ggplot(cat_lovers, mapping = aes(x = handedness)) +
  geom_bar()
```

```{r}
cat_lovers %>%
  mutate(handedness = fct_infreq(handedness)) %>%
  ggplot(mapping = aes(x = handedness)) +
  geom_bar()
```

##Make a date

```{r}
hotels %>%
  select(starts_with("arrival_"))
```

```{r}
library(glue)
hotels %>%
  mutate(
    arrival_date = glue("{arrival_date_year} {arrival_date_month} {arrival_date_day_of_month}")
    ) %>% 
  relocate(arrival_date)
```

```{r}
hotels %>%
  mutate(arrival_date = glue("{arrival_date_year} {arrival_date_month} {arrival_date_day_of_month}")) %>%
  count(arrival_date)
```

```{r}
hotels %>%
  mutate(arrival_date = glue("{arrival_date_year} {arrival_date_month} {arrival_date_day_of_month}")) %>%
  count(arrival_date) %>%
  ggplot(aes(x = arrival_date, y = n, group = 1)) +
  geom_line()
```

## Revised construct dates

```{r}
library(lubridate)
hotels %>%
  mutate(
    arrival_date = ymd(glue("{arrival_date_year} {arrival_date_month} {arrival_date_day_of_month}"))
    ) %>% 
  relocate(arrival_date)
```

```{r}
hotels %>%
  mutate(arrival_date = ymd(glue("{arrival_date_year} {arrival_date_month} {arrival_date_day_of_month}"))) %>% 
  count(arrival_date)
```

```{r}
hotels %>%
  mutate(arrival_date = ymd(glue("{arrival_date_year} {arrival_date_month} {arrival_date_day_of_month}"))) %>% 
  count(arrival_date) %>%
  ggplot(aes(x = arrival_date, y = n, group = 1)) +
  geom_line()
```

```{r}
hotels %>%
  mutate(arrival_date = ymd(glue("{arrival_date_year} {arrival_date_month} {arrival_date_day_of_month}"))) %>% 
  count(arrival_date) %>%
  ggplot(aes(x = arrival_date, y = n, group = 1)) +
  geom_smooth()
```
























