---
title: Classification Models
author: R package build
date: '2022-04-01'
slug: classification-models
categories: []
tags: []
---

```{r}
library(tidyverse)
library(ggplot2)
library(dplyr)
library(tidymodels)
library(ggridges)
```

```{r}
gender_submission <- read_csv("data/gender_submission.csv")
test <- read_csv("data/test.csv")
train <- read_csv("data/train.csv")
```

```{r}
test1 <- cbind(test, Survived = gender_submission$Survived)
```

```{r}
colSums(is.na(train))
```

```{r}
train_clean <- train %>%
    mutate(Age = if_else(is.na(Age), mean(Age, na.rm = TRUE), Age))

colSums(is.na(train_clean))
```

```{r}
colSums(is.na(test1))
```
```{r}
test_clean <- test1 %>% 
    na.omit()
```


```{r}
data_train <- train_clean %>% 
        select(-c(PassengerId, Name, Ticket, Embarked, Cabin)) %>% 
        mutate(Survived = as.factor(Survived),
           Pclass = as.factor(Pclass),
           Sex = as.factor(Sex),
           SibSp = as.factor(SibSp),
           Parch = as.factor(Parch))
```

```{r}
str(data_train)
```

```{r}
prop.table(table(data_train$Survived))
```

```{r}
train$Pclass <- as.factor(train$Pclass)
train$Survived <- as.factor(train$Survived)
train$Sex <- as.factor(train$Sex)
train$Embarked <- as.factor(train$Embarked)
```

```{r}
logistic.train <- glm(Survived~., data_train, family = "binomial") 
summary(logistic.train)
```

# Survavial rate of passangers

```{r}
ggplot(train, aes(x = Survived, fill = Survived)) + 
  geom_bar() + 
  labs(y = "Passenger Count",
       title = "Survival Rates") 

```

```{r}
prop.table(table(train$Survived))
```

# Survival rate by Sex 
```{r}
ggplot(data_train, aes(x = Sex, fill = Survived)) + 
  theme_bw() +
  geom_bar() +
  labs(y = "Passenger Count",
       title = "Survival Rates by Sex")
```

# Survival rate by ticket class
```{r}
ggplot(train, aes(x = Pclass, fill = Survived)) + 
  theme_bw() +
  geom_bar() +
  labs(y = "Passenger Count",
       title = "Titanic Survival Rates by Ticket Class")
```
# Survival rate of sex and ticket class
```{r}
ggplot(train, aes(x = Sex, fill = Survived)) + 
  theme_bw() +
  facet_wrap(~ Pclass) +
  geom_bar() +
  labs(y = "Passenger Count",
       title = "Titanic Survival Rates by Sex and Ticket Class")
```

# Data of age of passangers

```{r}
ggplot(train, aes(x = Age, fill = Survived)) +
  theme_bw() +
  geom_histogram(binwidth = 5) +
  labs(y = "Passenger Count",
       x = "Age",
       title = "Passanger Age Survival Rate")
```

# Survival rates by sex, ticket and age

```{r}
ggplot(train, aes(x = Age, fill = Survived)) +
  theme_bw() +
  facet_wrap(Sex ~ Pclass) +
  geom_density(alpha = 0.7) +
  labs(y = "Percent of Passangers",
       x = "Age",
       title = "Titanic Survival Rates by Sex, Ticket and Age")
```

```{r}
logistic.model <- glm(formula = Survived ~ Age + Pclass + Sex, family = "binomial", data = train)
summary(logistic.model)
```

```{r}
logistic.train <- glm(Survived~., data_train, family = "binomial") 
summary(logistic.train)
```

```{r}
Predicted_data <- data.frame(Age=seq(
  min(data_train$Age), max(data_train$Age),len=500))
```


```{r}
ggplot(data_train, aes(x=Age, y=Survived)) + geom_point() +
      stat_smooth(method="glm", color="blue", se=FALSE,
                method.args = list(family=binomial))
```













